// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://secturpyposdxwfyydci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlY3R1cnB5cG9zZHh3Znl5ZGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzAzMTksImV4cCI6MjA2MzA0NjMxOX0.4g05VvoS_y8vdz3P_nk-I7v9TWJQpQDRO2EviNwkgzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);